### ISSUE TITLE
Colons in function definition are highlighted as invalid

### ISSUE THREAD

**Issue by fredcallaway** [evhub/sublime-coconut#1]
Copying code from the tutorial demonstrates this problem.

```
def factorial(n:int, acc=1):  # this colon is marked invalid
    case n:
        match 0:
            return acc
        match _ is int if n > 0:
            return factorial(n-1, acc*n)
    else:
        raise TypeError("the argument to factorial must be an integer >= 0")
```

The scope name is `invalid.illegal.missing_section_begin.coconut`

**Comment by evhub** [comment]
@fredcallaway Good catch! I'll try to get a fix out for this as soon as I can.

**Comment by evhub** [comment]
@fredcallaway Fixed in https://github.com/evhub/sublime-coconut/releases/tag/v0.3.1!
