### ISSUE TITLE
Python 36 format strings cause the syntax highlighter to break.

### ISSUE THREAD

**Issue by pavelbraginskiy** [evhub/sublime-coconut#3]
Here is an example piece of Python code using Sublime's Python highlighter:

![Working python highlighting](https://i.imgur.com/g6jo0EB.png)

Here is the same code with the Coconut syntax highlighter:

![Not working Coconut highlighting](https://i.imgur.com/hhLUszy.png)

As you can see, a couple of odd things get highlighted, and the string literal doesn't seem to end.

**Comment by pavelbraginskiy** [comment]
On another slightly related note, the python syntax highlighter highlightes `%s` in strings and the coconut highlighter does not.

**Comment by evhub** [comment]
@pavelbraginskiy Thanks for the issue; I'll see what I can do in porting those features over!

**Comment by evhub** [comment]
@pavelbraginskiy This should now be fixed on sublime-coconut v1.0.4!
